package main

import (
	"flag"
	"fmt"
	"strings"
)

func main() { // Register command-line flags.
	numWords := flag.Int("words", 250, "maximum number of words to print")
	prefixLen := flag.Int("prefix", 1, "prefix length in words")
	baseText := `By an anonymous summons, an attempt has been made to convene you together—how inconsistent with the rules of propriety! how unmilitary! and how subversive of all order and discipline—let the good sense of the Army decide.
In the moment of this summons, another anonymous production was sent into circulation; addressed more to the feelings & passions, than to the reason & judgment of the Army. The Author of the piece, is entitled to much credit for the goodness of his Pen: and I could wish he had as much credit for the rectitude of his Heart—for, as Men see thro’ different Optics, and are induced by the reflecting faculties of the Mind, to use different means to attain the same end; the Author of the Address, should have had more charity, than to mark for Suspicion, the Man who should recommend Moderation and longer forbearance—or, in other words, who should not think as he thinks, and act as he advises. But he had another plan in view, in which candor and liberality of Sentiment, regard to justice, and love of Country, have no part; and he was right, to insinuate the darkest suspicion, to effect the blackest designs.
That the Address is drawn with great art, and is designed to answer the most insidious purposes. That it is calculated to impress the Mind, with an idea of premeditated injustice in the Sovereign power of the United States, and rouse all those resentments which must unavoidably flow from such a belief. That the secret Mover of this Scheme (whoever he may be) intended to take advantage of the passions, while they were warmed by the recollection of past distresses, without giving time for cool, deliberative thinking, & that composure of Mind which is so necessary to give dignity & stability to measures, is rendered too obvious, by the mode of conducting the business, to need other proof than a reference to the proceeding.
Thus much, Gentlemen, I have thought it incumbent on me to observe to you, to shew upon what principles I opposed the irregular and hasty meeting which was proposed to have been held on Tuesday last: and not because I wanted a disposition to give you every opportunity, consistent with your own honor, and the dignity of the Army, to make known your grievances. If my conduct heretofore, has not evinced to you, that I have been a faithful friend to the Army; my declaration of it at this time wd be equally unavailing & improper—But as I was among the first who embarked in the cause of our common Country—As I have never left your side one moment, but when called from you, on public duty—As I have been the constant companion & witness of your Distresses, and not among the last to feel, & acknowledge your Merits—As I have ever considered my own Military reputation as inseperably connected with that of the Army—As my Heart has ever expanded wth joy, when I have heard its praises—and my indignation has arisen, when the Mouth of detraction has been opened against it—it can scarcely be supposed, at this late stage of the War, that I am indifferent to its interests.
But—how are they to be promoted? The way is plain, says the anonymous Addresser—If War continues, remove into the unsettled Country—there establish yourselves, and leave an ungrateful Country to defend itself—But who are they to defend? Our Wives, our Children, our Farms and other property which we leave behind us. or—in this state of hostile separation, are we to take the two first (the latter cannot be removed) to perish in a Wilderness, with hunger cold & nakedness? If Peace takes place, never sheath your Sword says he until you have obtained full and ample Justice—this dreadful alternative, of either deserting our Country in the extremest hour of her distress, or turning our Army against it, (which is the apparent object, unless Congress can be compelled into an instant compliance) has something so shocking in it, that humanity revolts at the idea. My God! What can this Writer have in view, by recommending such measures? Can he be a friend to the Army? Can he be a friend to this Country? Rather, is he not an insidious Foe? Some Emissary, perhaps, from New York, plotting the ruin of both, by sowing the seeds of discord & separation between the Civil & Military powers of the Continent? And what a Compliment does he pay to our understandings, when he recommends measures in either alternative, impracticable in their nature?
But here, Gentlemen, I will drop the curtain; because it wd be as imprudent in me to assign my reasons for this opinion, as it would be insulting to your conception, to suppose you stood in need of them. A moments reflection will convince every dispassionate Mind of the physical impossibility of carrying either proposal into execution.
There might, Gentlemen, be an impropriety in my taking notice, in this Address to you, of an anonymous production—but the manner in which that performance has been introduced to the Army—the effect it was intended to have, together with some other circumstances, will amply justify my observations on the tendency of that Writing. With respect to the advice given by the Author—to suspect the Man, who shall recommend moderate measures and longer forbearance—I spurn it—as every Man, who regards that liberty, & reveres that Justice for which we contend, undoubtedly must—for if Men are to be precluded from offering their sentiments on a matter, which may involve the most serious and alarming consequences, that can invite the consideration of Mankind; reason is of no use to us—the freedom of Speech may be taken away—and, dumb & silent we may be led, like sheep, to the Slaughter.
I cannot, in justice to my own belief, & what I have great reason to conceive is the intention of Congress, conclude this Address, without giving it as my decided opinion; that that Honble Body, entertain exalted sentiments of the Services of the Army; and, from a full conviction of its Merits & sufferings, will do it compleat Justice: That their endeavors, to discover & establish funds for this purpose, have been unwearied, and will not cease, till they have succeeded, I have not a doubt. But, like all other large Bodies, where there is a variety of different Interests to reconcile, their deliberations are slow. Why then should we distrust them? and, in consequence of that distrust, adopt measures, which may cast a shade over that glory which, has been so justly acquired; and tarnish the reputation of an Army which is celebrated thro’ all Europe, for its fortitude and Patriotism? and for what is this done? to bring the object we seek for nearer? No! most certainly, in my opinion, it will cast it at a greater distance.
For myself (and I take no merit in giving the assurance, being induced to it from principles of gratitude, veracity & justice)—a grateful sense of the confidence you have ever placed in me—a recollection of the Chearful assistance, & prompt obedience I have experienced from you, under every vicisitude of Fortune, and the sincere affection I feel for an Army, I have so long had the honor to Command, will oblige me to declare, in this public & solemn manner, that, in the attainment of compleat justice for all your toils & dangers, and in the gratification of every wish, so far as may be done consistently with the great duty I owe my Country, and those powers we are bound to respect, you may freely command my services to the utmost of my abilities.
While I give you these assurances, and pledge my self in the most unequivocal manner, to exert whatever ability I am possesed of, in your favor—let me entreat you, Gentlemen, on your part, not to take any measures, which, viewed in the calm light of reason, will lessen the dignity, & sully the glory you have hitherto maintained—let me request you to rely on the plighted faith of your Country, and place a full confidence in the purity of the intentions of Congress; that, previous to your dissolution as an Army they will cause all your Accts to be fairly liquidated, as directed in their resolutions, which were published to you two days ago—and that they will adopt the most effectual measures in their power, to render ample justice to you, for your faithful and meritorious Services. And let me conjure you, in the name of our common Country--as you value your own sacred honor—as you respect the rights of humanity, & as you regard the Military & national character of America, to express your utmost horror & detestation of the Man who wishes, under any specious pretences, to overturn the liberties of our Country, & who wickedly attempts to open the flood Gates of Civil discord, & deluge our rising Empire in Blood.
By thus determining--& thus acting, you will pursue the plain & direct Road to the attainment of your wishes. You will defeat the insidious designs of our Enemies, who are compelled to resort from open force to secret Artifice. You will give one more distinguished proof of unexampled patriotism & patient virtue, rising superior to the pressure of the most complicated sufferings; And you will, by the dignity of your Conduct, afford occasion for Posterity to say, when speaking of the glorious example you have exhibited to man kind, "had this day been wanting, the World had never seen the last stage of perfection to which human nature is capable of attaining."`
	c := NewChain(*prefixLen)
	c.Build(strings.NewReader(baseText))
	text := c.Generate(*numWords) // Generate text.
	fmt.Println(text)             // Write text to standard output.
}

//
